app/app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
]

if settings.APPLICATION_STAGE == settings.STAGE_OF_DEVELOPING:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/dashboard/urls.py
# index/urls.py
from django.urls import include, path
from . import views, views_ajax_custom, views_ajax_index
from django.contrib.auth import views as auth_views
from django.conf.urls import url

urlpatterns = [
    path('custom/get_settings', views_ajax_custom.get_settings, name='custom_get_settings'),
    path('custom/get_settings_summary', views_ajax_custom.get_settings_summary, name='custom_get_settings_summary'),
    path('custom/get_settings_data', views_ajax_custom.get_settings_data, name='custom_get_settings_data'),
    path('custom/get_matched_data', views_ajax_custom.get_matched_data, name='custom_get_matched_data'),
    path('custom/get_quiz_video_info', views_ajax_custom.get_quiz_video_info, name='custom_get_quiz_video_info'),
    path('custom/get_commercial_info', views_ajax_custom.get_commercial_info, name='custom_get_commercial_info'),
    path('index/get_settings', views_ajax_index.get_settings, name='index_get_settings'),
    path('index/get_settings_chart_data', views_ajax_index.get_chart_data, name='index_get_chart_data'),
    path('index/get_initial_commercial_data', views_ajax_index.get_initial_commercial_data, name='index_get_initial_commercial_data'),
    path('index/get_commercial_search_data', views_ajax_index.get_commercial_search_data, name='index_get_commercial_search_data'),
]

app/dashboard/models.py
from django.db import models

# Create your models here.

app/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from client.models import TargetAge, TargetInterest, TargetGender, TargetLocation

# Create your models here.


class Info(models.Model):
    USER_ACTIVE = 'A'
    USER_INACTIVE = 'I'

    USER_STATUS = [
        (USER_ACTIVE, 'ACTIVE'),
        (USER_INACTIVE, 'INACTIVE')
    ]

    user_status = models.CharField(
        max_length=1,
        default=USER_ACTIVE,
        choices=USER_STATUS
    )
    email = models.CharField(max_length=100, null=True)
    mobile = models.CharField(max_length=50, null=True)
    bank_type = models.CharField(max_length=30, null=True)
    account_number = models.CharField(max_length=70, null=True)
    age = models.IntegerField(null=True)
    reg_at = models.DateField(default=timezone.now)


class Interest(models.Model):
    '''
    INTEREST SUB-CATEGORY SHOULD BE CONSIDERED FOR CLIENT PREFERENCE AT A LATER STAGE OF THE catchya-app development.
    Users of the app should only be able to choose INTEREST MAIN-CATEGORY for ease of completion.
    '''
    info = models.ForeignKey(Info, on_delete=models.CASCADE)
    interest = models.CharField(
        max_length=2,
        default=TargetInterest.INTEREST_MAIN_NONE,
        choices=TargetInterest.INTEREST_MAIN_CHOICES
    )


class AgeGroup(models.Model):
    info = models.ForeignKey(Info, on_delete=models.CASCADE)
    age = models.CharField(
        max_length=2,
        default=TargetAge.AGE_GROUP_0,
        choices=TargetAge.AGE_GROUP_CHOICES
    )


class Gender(models.Model):
    info = models.ForeignKey(Info, on_delete=models.CASCADE)
    gender = models.CharField(
        max_length=2,
        default=TargetGender.GENDER_0,
        choices=TargetGender.GENDER_CHOICES
    )


class Location(models.Model):
    info = models.ForeignKey(Info, on_delete=models.CASCADE)
    location = models.CharField(
        max_length=2,
        default=TargetLocation.LOCATION_0,
        choices=TargetLocation.LOCATION_CHOICES
    )
    

class LoginInfo(models.Model):
    info = models.ForeignKey(Info, on_delete=models.CASCADE)
    login_ip = models.CharField(max_length=50)    
    last_login_at = models.DateField(default=timezone.now)

app/dashboard/views.py
from django.shortcuts import render

app/dashboard/templates/dashboard/custom/settings_initial.html
{% if settings_list %}
{% for settings in settings_list%}
    <option value={{ settings.id }}>{{ settings.title }}</option>
{% endfor %}
{% endif %}

app/dashboard/templates/dashboard/custom/settings_quiz_video.html
{% if quiz_list%}
{% for quiz in quiz_list %}
<option value="q_{{ quiz.id }}">{{ quiz.title }}</option>
{% endfor %}
{% endif %}
{% if video_list%}
{% for video in videos_list %}
<option value="v_{{ video.id }}">{{ video.title }}</option>
{% endfor %}
{% endif %}

app/dashboard/templates/dashboard/custom/settings_summary.html
{% if settings_list %}
<div class="col-xl-2 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">금일 광고 수</h5>
                    <span class="h2 font-weight-bold mb-0">
                    {% for settings in settings_list%}
                        {{ settings.exposed_size }}
                    {% endfor %}
                    </span>
                </div>
                <div class="col-auto">
                    <div class="icon icon-shape bg-danger text-white rounded-circle shadow">
                        <i class="fa fa-chart-bar"></i>
                    </div>
                </div>
            </div>
            <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                <span class="text-nowrap">Since last month</span>
            </p>
        </div>
    </div>
</div>
<div class="col-xl-2 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">진행률</h5>
                    <span class="h2 font-weight-bold mb-0">
                    {% for settings in settings_list%}
                        {{ settings.exposed_size }}/{{settings.target_size}}
                    {% endfor %}</span>
                </div>
                <div class="col-auto">
                    <div class="icon icon-shape bg-warning text-white rounded-circle shadow">
                        <i class="fa fa-chart-pie"></i>
                    </div>
                </div>
            </div>
            <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 3.48%</span>
                <span class="text-nowrap">Since last week</span>
            </p>
        </div>
    </div>
</div>
<div class="col-xl-2 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">연령 타겟 현황</h5>
                    {% if  target_a.count > 2 %}
                        <span class="h5 font-weight-bold mb-0">
                    {% else %}
                        <span class="h2 font-weight-bold mb-0">
                    {% endif %}
                    
                        {% for age in target_a%}
                            {{ age.get_age_display }}
                        {% endfor %}
                    </span>
                </div>
                <div class="col-auto">
                    <div class="icon icon-shape bg-yellow text-white rounded-circle shadow">
                        <i class="fa fa-users"></i>
                    </div>
                </div>
            </div>
            <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-warning mr-2"><i class="fa fa-arrow-down"></i> 1.10%</span>
                <span class="text-nowrap">Since yesterday</span>
            </p>
        </div>
    </div>
</div>
<div class="col-xl-2 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">관심사 타겟 현황</h5>
                    <span class="h2 font-weight-bold mb-0">
                        {% for interest in target_i%}
                            {{ interest.get_interest_display }}
                        {% endfor %}
                    </span>
                </div>
            </div>
            <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 12%</span>
                <span class="text-nowrap">Since last month</span>
            </p>
        </div>
    </div>
</div>
<div class="col-xl-2 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">지역 타겟 현황</h5>
                    <span class="h2 font-weight-bold mb-0">
                        {% for location in target_l%}
                            {{ location.get_location_display }}
                        {% endfor %}
                    </span>
                </div>
            </div>
            <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 12%</span>
                <span class="text-nowrap">Since last month</span>
            </p>
        </div>
    </div>
</div>
<div class="col-xl-2 col-lg-6">
    <div class="card card-stats mb-4 mb-xl-0">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">성별 타겟 현황</h5>
                    <span class="h2 font-weight-bold mb-0">
                        {% for gender in target_g%}
                            {{ gender.get_gender_display }}
                        {% endfor %}
                    </span>
                </div>
            </div>
            <p class="mt-3 mb-0 text-muted text-sm">
                <span class="text-success mr-2"><i class="fa fa-arrow-up"></i> 12%</span>
                <span class="text-nowrap">Since last month</span>
            </p>
        </div>
    </div>
</div>
{% else %}
    <div class="col-xl-12 card card-stats">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h5 class="card-title text-uppercase text-muted mb-0">광고 이력이 존재하지 않습니다.</h5>
                </div>
            </div>
        </div>
    </div>
{% endif %}